apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-app
  labels:
{{ include "fruitapp.labels" . | indent 4 }}
    app: {{ .Release.Name }}-{{ .Chart.Name }}-app
spec:
  containers:
    - name: {{ .Release.Name }}-{{ .Chart.Name }}-app
      image: hashicorp/http-echo
      args:
        - "-text={{ .Values.pod.text }}"
