{{- if .ingress_enabled true }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: {{ .Values.ingress.path }}
          backend:
            serviceName: {{ .Release.Name }}-{{ .Chart.Name }}-service
            servicePort: 5678
{{- end }}