---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-app
  ports:
    - port: 5678 # Default port for image