---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
spec:
  {{- if .Values.ingress_enabled false -}}
  type: LoadBalancer
  {{- end -}}
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-app
  ports:
    - port: 5678 # Default port for image